server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;
    location ~* ^/(\.env|\.git|\.ssh|\.aws|wp-|.*\.php) {
        return 404;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
